# Generated by Django 5.2.10 on 2026-01-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="fps",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
