# Generated by Django 5.2.10 on 2026-03-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_video_fps"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="frames_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="numFrames",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
