# Generated by Django 5.2.10 on 2026-03-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_video_frames_data_video_numframes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="frames_data",
            new_name="frames_timestamps",
        ),
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
