# Generated by Django 6.0.2 on 2026-04-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_frames_data_video_frames_timestamps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='is_goal',
            field=models.BooleanField(default=False),
        ),
    ]
